### PR TITLE
FIX: DataObject UploadField 

### PR DESCRIPTION
**Pull request by a2nt**
+ Form_fileSelectForm was broken
+ parent object field needs to be updated using new cropped image

### CODE REVIEW

**Comment by DoggersHusky** [comment]
Thanks for this! I will try to review/test shortly!

**Comment by a2nt** [comment]
I have also reviewed more code, made some optimizations and replaced XHtmlRequest with axios.

The important thing is that application/x-www-form-urlencoded form won't let you send big images while multipart/form-data allows it and latter using axios we can add a progress bar and chunk loading.

I have tested 10 Mb images and it works great with multipart/form-data, but doesn't work properly with application/x-www-form-urlencoded

**Comment by a2nt** [comment]
#3 #10

**Comment by DoggersHusky** [comment]
Again, thanks very much for this! I will review and test here in a moment!

**Pull request merged**
